# Generated by Django 6.0.6 on 2026-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('minimum_age', models.IntegerField(default=0)),
                ('maximum_income', models.IntegerField(blank=True, null=True)),
                ('farmer_required', models.BooleanField(default=False)),
                ('student_required', models.BooleanField(default=False)),
                ('disability_required', models.BooleanField(default=False)),
                ('widow_required', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
