# Generated by Django 6.0.6 on 2026-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='farmer_required',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='student_required',
        ),
        migrations.AddField(
            model_name='scheme',
            name='required_occupation',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('Farmer', 'Farmer'), ('Student', 'Student'), ('Salaried Employee', 'Salaried Employee'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Homemaker', 'Homemaker'), ('Retired', 'Retired')], max_length=50),
        ),
    ]
