# Generated by Django 6.0.6 on 2026-06-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_remove_scheme_farmer_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='official_link',
            field=models.URLField(blank=True),
        ),
    ]
