# Generated by Django 6.0.6 on 2026-06-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_scheme_official_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='required_occupation',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('Farmer', 'Farmer'), ('Student', 'Student'), ('Salaried Employee', 'Salaried Employee'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Homemaker', 'Homemaker'), ('Retired', 'Retired'), ('Widow', 'Widow'), ('Disabled', 'Disabled')], max_length=50),
        ),
    ]
