# Generated by Django 6.0.6 on 2026-06-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilitySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
