# Generated by Django 6.0.6 on 2026-06-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibilitysearch',
            options={'verbose_name': 'Eligibility Search', 'verbose_name_plural': 'Eligibility History'},
        ),
    ]
